import { Field, InputType } from "@nestjs/graphql";
import {
  IsBoolean,
  IsNotEmpty,
  IsOptional,
  IsString,
  MaxLength,
  MinLength,
} from "class-validator";

@InputType()
export class CreateArticleInput {
  @Field()
  @IsString()
  @IsNotEmpty()
  @MinLength(5)
  title: string;

  @Field({ nullable: true })
  @IsString()
  @IsOptional()
  @IsNotEmpty()
  @MaxLength(300)
  description?: string;

  @Field()
  @IsString()
  @IsNotEmpty()
  body: string;

  @Field()
  @IsBoolean()
  @IsOptional()
  // biome-ignore lint/style/noInferrableTypes: this annotation is needed for docs generated by swagger
  published: boolean = false;
}
