import { ApiProperty } from "@nestjs/swagger";

export class CreateArticleDto {
  @ApiProperty()
  title: string;

  @ApiProperty({ required: false })
  description?: string;

  @ApiProperty()
  body: string;

  @ApiProperty({ required: false, default: false })
  // biome-ignore lint/style/noInferrableTypes: this annotation is needed for docs generated by swagger
  published: boolean = false;
}
